
name: CI

on: push

env:
  GCC_VERSION: "11.2.0"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Show basic system info
        run: |
          uname -a
          lscpu
          free -h
          df -h
          ip a
          ls
          pwd

      - name: Download and decompress gcc source file
        run: |
          gcc_version=${{ env.GCC_VERSION }}
          wget -q https://ftp.gnu.org/gnu/gcc/gcc-${gcc_version}/gcc-${gcc_version}.tar.gz > /dev/null
          tar xvf gcc-${gcc_version}.tar.gz > /dev/null
          ls
      - name: Docker build
        run: |
          docker run -v ${PWD}:/workspace -w=/workspace centos:7 bash script_in_docker.sh
      
      - name: Inspect size
        run: |
          pwd
          ls
          du -h -d2 ${PWD}
          df -h

      - uses: actions/upload-artifact@v2
        with:
          name: gcc-build-artifact
          path: gcc-${{ env.GCC_VERSION }}

      - uses: actions/upload-artifact@v2
        with:
          name: toolchain-artifact
          path: toolchains


