name: CI

on: push

env:
  IMAGE_REGISTRY: "ghcr.io"
  REGISTRY_USER: "${{ github.repository_owner }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "centos7-gcc"

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        gcc_version: ["11.2.0", "9.4.0", "8.5.0", "10.3.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Show basic system info
        run: |
          uname -a
          lscpu
          free -h
          df -h
          ip a
          ls
          pwd

      - name: Download gcc source
        run: |
          bash ci/download_gcc.sh ${{ matrix.gcc_version }}
          ls -l

      - name: Docker build
        run: |
          # bash ci/run_docker_oneline.sh
          mkdir toolchains
          echo gcc-${{ matrix.gcc_version }} > toolchains/gcc_version
      
      # - name: Inspect size
      #   run: |
      #     pwd
      #     ls
      #     du -h -d1 ${PWD}
      #     tar -czvf toolchains.tar.gz toolchains
      #     tar -czvf gcc-${{ matrix.gcc_version }}-build.tar.gz gcc-${{ matrix.gcc_version }}-build

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: gcc-${{ matrix.gcc_version }}-toolchains
      #     path: toolchains.tar.gz

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: gcc-${{ matrix.gcc_version }}-build
      #     path: gcc-${{ matrix.gcc_version }}-build.tar.gz

      - name: Login docker 
        run: |
          echo ${{ env.REGISTRY_TOKEN }} | docker login ${{ env.IMAGE_REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin

      - name: Docker build
        run: |
          docker build -t ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.gcc_version }} .

      - name: Push docker image
        run: |
          docker push ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.gcc_version }}

      - name: Test docker image
        run: |
          docker run --rm ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.gcc_version }} ls
          docker run --rm ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.gcc_version }} ls -la
          docker run --rm ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.gcc_version }} pwd
          docker run --rm ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.gcc_version }} ls /root
          docker run --rm ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.gcc_version }} cat /root/toolchains/gcc_version
          