name: CI

on: push

env:
  GCC_VERSION: "11.2.0"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Show basic system info
        run: |
          uname -a
          lscpu
          free -h
          df -h
          ip a
          ls
          pwd

      - name: Download gcc source
        run: |
          bash ci/download_gcc.sh ${{ env.GCC_VERSION }}

      - name: Docker build
        run: |
          bash ci/run_docker_oneline.sh
      
      - name: Inspect size
        run: |
          pwd
          ls
          du -h -d1 ${PWD}

      - uses: actions/upload-artifact@v2
        with:
          name: toolchain-artifact
          path: toolchains

      - uses: actions/upload-artifact@v2
        with:
          name: gcc-build-artifact
          path: gcc-${{ env.GCC_VERSION }}

